defaults:
  - human_env
  - _self_

env_id: PickPlaceHumanCart
table_full_size:
  - 1.5
  - 2.0
  - 0.05
table_friction:
  - 1.0
  - 5e-3
  - 1e-4
goal_dist: 0.1
object_gripped_reward: -1.0
obstacle_placement_initializer: null
human_animation_names: 
  - CMU/62_01
  - CMU/62_03
  - CMU/62_04
  - CMU/62_07
  - CMU/62_09
  - CMU/62_10
  - CMU/62_12
  - CMU/62_13
  - CMU/62_14
  - CMU/62_15
  - CMU/62_16
  - CMU/62_18
  - CMU/62_19