name: hrgym
channels:
  - conda-forge
dependencies:
  - pip>=22.0.4
  - python=3.8
  - setuptools==65.5.0
  - wheel=0.38.4  # Fix for Issue #160: https://github.com/openai/gym/issues/3202#issuecomment-1513593788
  - pip:
    # works for regular pip packages
    - bvh==0.3
    - stable_baselines3==1.5.0
    - robosuite==1.3.2
    - mujoco-py==2.1.2.14
    - opencv_python==4.5.5.64
    - pin
    - pybullet==3.2.1
    - meshcat==0.3.2
    - numpy<=1.23.4
    - scipy==1.8.0
    - numba<=0.53.1
    - wandb==0.13.1
    - flake8==5.0.4
    - black==22.6.0
    - patchelf==0.15.0
    - h5py==3.7.0
    - tensorboard==2.10.0
    - pydocstyle==6.1.1
    - mypy==0.971
    - pytest==7.1.1
    - sphinx_rtd_theme
    - sphinx-autoapi
    - graphviz
    - hydra-core==1.3.2
    - hydra-ray-launcher==1.2.0
