name: hrgym
channels:
  - conda-forge
dependencies:
  - pip>=22.0.4
  - python=3.13
  - setuptools # ==65.5.0
  - wheel # =0.38.4  # Fix for Issue #160: https://github.com/openai/gym/issues/3202#issuecomment-1513593788
  - pip:
    ## robosuite requirements
    - robosuite==1.5.1
    - robosuite-models==1.0.0
    - gymnasium
    - mink==0.0.12  # Only needed for GR1 robot whole-body IK, not required for Panda
    - h5py
    - usd-core
    - mujoco>=3.3.0
    ## hrgym requirements
    - bvh==0.3
    - opencv_python
    - pin
    - pybullet
    - meshcat
    - numpy~=2.2
    - scipy
    - numba
    - patchelf
    ## Testing and Linting
    - pydocstyle
    - flake8
    - black
    - pytest
    - mypy
    ## Training requirements
    # - stable_baselines3==1.5.0
    # - wandb
    # - tensorboard==2.10.0
    - hydra-core
    - hydra-ray-launcher
    ## Documentation
    - graphviz
    - sphinx_rtd_theme
    - sphinx-autoapi
