[metadata]
name = human_robot_gym
author = Jakob Thumm
author_email = jakob.thumm@tum.de
version = 0.1.0
description="human-robot-gym is an extension to the robosuite package\
             to train RL algorithms on robots in human environments."
url = TODO

[options]
install_requires =
    bvh
    mujoco>=3.3.0
    opencv_python
    robosuite>=1.5.1
    # stable_baselines3==1.5.0
    pin
    pybullet
