[metadata]
name = human_robot_gym
author = Jakob Thumm
author_email = jakob.thumm@tum.de
version = 0.1.0
description="human-robot-gym is an extension to the robosuite package\
             to train RL algorithms on robots in human environments."
url = TODO

[options]
install_requires =
    ## robosuite requirements
    robosuite==1.5.1
    robosuite-models==1.0.0
    gymnasium
    mink==0.0.12  # Only needed for GR1 robot whole-body IK, not required for Panda
    h5py
    usd-core
    mujoco>=3.3.0
    ## hrgym requirements
    bvh==0.3
    opencv_python
    pin
    pybullet
    meshcat
    numpy~=2.2
    scipy
    numba
    mypy
    patchelf
