defaults:
  - default/human_robot_handover_cart@_here_
  - _self_

robot_base_offset:
  - 0.0
  - 0.0
  - 0.0
use_camera_obs: false
use_object_obs: true
has_offscreen_renderer: false
render_camera: null
horizon: 1000
hard_reset: false
done_at_collision: false
done_at_success: true
human_animation_names:
  - HumanRobotHandover/0
  - HumanRobotHandover/1
  - HumanRobotHandover/2
  - HumanRobotHandover/3
  - HumanRobotHandover/4
  - HumanRobotHandover/5
  - HumanRobotHandover/6
  - HumanRobotHandover/7
human_animation_freq: 90
n_targets_sampled_per_100_steps: 3
object_at_target_reward: 0.0
object_gripped_reward: -0.25
collision_reward: -1.0
human_rand:
  - 0.0
  - 0.2
  - 0.1