# Parameters from parent configs commented out
defaults:
  - base/reach_human@_here_

kwargs:
  robot_base_offset:
    - 0.0
    - 0.0
    - 0.0
# env_configuration: default
# controller_configs: null
# gripper_types: default
# initialization_noise: default
# table_full_size: 
#   - 1.5
#   - 2.0
#   - 0.05
  table_friction: 
    - 1.0
    - 5e-3
    - 1e-4
  use_camera_obs: false
  use_object_obs: true
# reward_scale: 1.0
# reward_shaping: false
# goal_dist: 0.1
  collision_reward: 0
# goal_reward: 1
# object_placement_initializer: null
# obstacle_placement_initializer: null
# has_renderer: false
  has_offscreen_renderer: false
  render_camera: null
# render_collision_mesh: false
# render_visual_mesh: true
# render_gpu_device_id: -1
  control_freq: 5
  horizon: 100
  ignore_done: true
  hard_reset: false
  camera_names: frontview
# camera_heights: 256
# camera_widths: 256
# camera_depths: false
# camera_segmentations: null
# renderer: mujoco
# renderer_config: null
# use_failsafe_controller: true
# visualize_failsafe_controller: false
# visualize_pinocchio: false
# control_sample_time: 0.004
# human_animation_names: 
#   - "62_01"
#   - "62_03"
#   - "62_04"
#   - "62_07"
#   - "62_09"
#   - "62_10"
#   - "62_12"
#   - "62_13"
#   - "62_14"
#   - "62_15"
#   - "62_16"
#   - "62_18"
#   - "62_19"
# base_human_pos_offset: 
#     0.0
#     0.0
#     0.0
# human_animation_freq: 120
# human_rand:
#   - 0.0
#   - 0.0
#   - 0.0
  safe_vel: 0.01
# randomize_initial_pos: false
  self_collision_safety: 0.012
# seed: 0
# verbose: false
# done_at_collision: false
  done_at_success: true