defaults:
  - robot: schunk
  - environment: reach_human
  - wrappers: safe
  - training: parallel_training
  - algorithm: ppo
  - wandb_run: default_wandb
  - _self_
  - consistent_seeding
#  - eval  # uncomment to evaluate with renderer instead of training

training:
  run_type: wandb
  obs_keys:
    - object-state
    - goal_difference
environment:
  reward_shaping: true
