defaults:
  - robot: schunk
  - environment: pick_place_human_cart
  - wrappers: safe_ik_action_imitation
  - algorithm: sac
  - expert: pick_place
  - training: expert_imitation_training
  - wandb_run: default_wandb
  - _self_
  - consistent_seeding
#  - eval

training:
  run_type: wandb
  n_envs: 10
  obs_keys:
    - object_gripped
    - vec_to_next_objective
    - robot0_gripper_qpos
    - robot0_gripper_qvel
    - eef_to_human_head
    - eef_to_human_lh
    - eef_to_human_rh
wrappers:
  ik_position_delta:
    action_limit: 0.1
  action_based_expert_imitation_reward:
    alpha: 0.1
    beta: 0.5
    iota_m: 0.05
    iota_g: 0.1
