defaults:
  - robot: schunk
  - environment: pick_place_human_cart
  - wrappers: safe_ik
  - expert: pick_place
  - training: expert_imitation_training
  - consistent_seeding
  - _self_
  - eval

environment:
  verbose: true
  done_at_success: true
training:
  obs_keys:
    - object_gripped
    - vec_to_next_objective
    - robot0_gripper_qpos
    - eef_to_human_head
    - eef_to_human_lh
    - eef_to_human_rh
wrappers:
  ik_position_delta:
    action_limit: 0.1
expert:
  signal_to_noise_ratio: 0.98


dataset_name: däscht
start_episode_index: 0
n_episodes: 200
n_threads: 1
load_ep_index: null
