defaults:
  - robot: schunk
  - environment: pick_place_human_cart
  - wrappers: safe_ik
  - expert: pick_place_human_cart
  - run: expert_imitation_training
  - consistent_seeding
  - _self_
#  - eval

environment:
  verbose: true
  done_at_success: true
run:
  obs_keys:
    - object_gripped
    - vec_eef_to_object
    - vec_eef_to_target
    - gripper_aperture
    - dist_eef_to_human_head
    - dist_eef_to_human_lh
    - dist_eef_to_human_rh
wrappers:
  ik_position_delta:
    action_limit: 0.1
expert:
  signal_to_noise_ratio: 0.98
  seed: ${run.seed}


dataset_name: pick-place-dataset
start_episode_index: 0
n_episodes: 200
n_threads: 1
load_episode_index: null
