enabled: true
kwargs:
  action_limits:
    - - -0.15
      - -0.15
      - -0.15
    - - 0.15
      - 0.15
      - 0.15
  x_output_max: 1
  x_position_limits: null
  residual_threshold: 1e-3
  max_iter: 50
