learning_rate: 5e-4
batch_size: 128
learning_starts: 1000
gamma: 0.99
tau: 5e-3
train_freq:
  - 1
  - episode
gradient_steps: -1
action_noise: null
ent_coef: auto_0.2
target_entropy: auto
use_sde: false
sde_sample_freq: -1
target_update_interval: 1
use_sde_at_warmup: false
policy_kwargs:
  net_arch:
    - 64
    - 64
    - 64
replay_buffer_kwargs:
  n_sampled_goal: 4
  goal_selection_strategy: future
  online_sampling: true
buffer_size: 1e6
