# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.0
delay: 0.0

# Names of joints in correct outputted order
joint_names: [
  "L_Hip", "R_Hip", "Torso", "L_Knee", "R_Knee",
  "Spine", "L_Ankle", "R_Ankle", "Chest", "L_Toe",
  "R_Toe", "Neck", "L_Thorax", "R_Thorax", "Head",
  "L_ShouLder", "R_ShouLder", "L_Elbow", "R_Elbow", "L_Wrist",
  "R_Wrist", "L_Hand", "R_Hand"
]

joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2
]

joint_a_max: [
  20, 20, 20, 30, 30,
  25, 30, 30, 20, 30,
  30, 25, 25, 25, 25,
  50, 50, 50, 50, 50,
  50, 50, 50
]

bodies:
  - name: "L_UpperArm" 
    proximal: "L_ShouLder"
    distal: "L_Elbow"
    thickness: 0.1

  - name: "L_LowerArm"
    proximal: "L_Elbow"
    distal: "L_Wrist"
    thickness: 0.1

  - name: "L_Hand"
    proximal: "L_Wrist"
    distal: "L_Hand"
    thickness: 0.205

  - name: "R_UpperArm" 
    proximal: "R_ShouLder"
    distal: "R_Elbow"
    thickness: 0.1

  - name: "R_LowerArm"
    proximal: "R_Elbow"
    distal: "R_Wrist"
    thickness: 0.1

  - name: "R_Hand"
    proximal: "R_Wrist"
    distal: "R_Hand"
    thickness: 0.205

  - name: "Torso"
    proximal: "Torso"
    distal: "Neck"
    thickness: 0.2 # Lays in 97% quantiLe according to https://www.rki.de/DE/Content/Gesundheitsmonitoring/Gesundheitsberichterstattung/GBEDownLoadsB/KiGGS_ReferenzperzentiLe.pdf?__bLob=pubLicationFiLe
  
  - name: "Head"
    proximal: "Neck"
    distal: "Head"
    thickness: 0.2

extremities:
  - name: "L_Arm"
    base: "L_ShouLder"
    end: "L_Hand"
    length: 0.8
    
  - name: "R_Arm"
    base: "R_ShouLder"
    end: "R_Hand"
    length: 0.8